services:
  user_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3308:3308"
    volumes:
      - ./mysql:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8081:8081"